name: Build & Deploy to Digital Ocean
on:
  push:
    branches: [develop]
    
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Deploy Theme
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}}
        password: ${{secrets.SSH_PASSWORD}}
        username: ${{secrets.SSH_USER}}

        script: |
          cd ../home/tomorrow/wp-content/themes/tomorrow-agency
          git pull
          echo 'pulled form repo'
